### ISSUE TITLE
from e3dc import E3DC -> Error

### ISSUE THREAD

**Issue by Niwla23** [fsantini/python-e3dc#11]
´´´python
from e3dc import E3DC
Traceback (most recent call last):
  File "/home/alwin/Dokumente/python/e3dc-control/e3dc.py", line 1, in <module>
    from e3dc import E3DC
  File "/home/alwin/Dokumente/python/e3dc-control/e3dc.py", line 1, in <module>
    from e3dc import E3DC
ImportError: cannot import name 'E3DC'´´´
Python 3.6.9
 Maybe outdated README?

**Comment by fsantini** [comment]
I assume you are on the correct python3 branch. It works for me.

I think you shouldn't call your script e3dc.py because it might confuse the interpreter

**Comment by Niwla23** [comment]
Oh i am so damn dumb :smile:
